version: "3"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    container_name: prometheusz
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    volumes:
      - "./prometheus:/etc/prometheus"
      - "prometheus_data:/prometheus"

  grafana:
    container_name: grafanaz
    image: grafana/grafana:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "./grafana/provisioning/:/etc/grafana/provisioning/"
      - "grafana_data:/var/lib/grafana"
    ports:
      -  3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana