global:
  scrape_interval: 15s 
  scrape_timeout: 10s

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - localhost:9090

- job_name: steam-deck-exporter
  metrics_path: /metrics
  static_configs:
    - targets:
        - steamdeck.local:9100 # replace with Steamdeck IP if steamdeck.local doesn't resolve on your LAN
